language: python
python:
  - "3.13"

dist: jammy

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - pip install -r requirements.txt
  - tox --parallel || travis_terminate 1

branches:
  only:
    - dev
