version: 0.1
dev:
  global:
    parameters:
      region: us-west-2
      stack_name: searchlight-cdc-dev
  deploy:
    parameters:
      capabilities: CAPABILITY_IAM
      confirm_changeset: true
      image_repositories: []
      s3_bucket: la-lambda-deploys
      s3_prefix: searchlight-cdc-dev
