# Tox (https://tox.readthedocs.io/) is a tool for running tests in multiple virtualenvs.

[tox]
envlist =
    lint-py,
    test
skipsdist = True

[testenv]
allowlist_externals = *

[testenv:test]
commands = make test-unit

[testenv:lint-py]
commands = make check
